### ISSUE TITLE
scim-patch partial match doesn't work

### ISSUE THREAD

**Issue by KareemMasoud** [thomaspoignant/scim-patch#175]
**Describe the bug**
Sending a request using patch with a partial match to the `value` attribute does not complete the operation passed in the request.
Using this example request from [ietf rfc7644](https://datatracker.ietf.org/doc/html/rfc7644#section-3.5.2):

```json
{ "schemas":
       ["urn:ietf:params:scim:api:messages:2.0:PatchOp"],
     "Operations":[
       {
        "op":"add",
        "path":"members",
        "value":[
         {
           "display": "Babs Jensen",
           "$ref":
   "https://example.com/v2/Users/2819c223...413861904646",
           "value": "2819c223-7f76-453a-919d-413861904646"
         }
        ]
       },
       ... + additional operations if needed ...
     ]
   }
```
Having the 'value' attribute only have either the 'display' or 'value' sub-attribute (and not both) does not complete the operation.

**To Reproduce**

Following the above example, let's also assume that the 'display' attribute is an email field and that a user exists, send the request with that user's email address - in the display attribute - with (e.g. a `remove` operation) and you will see that the user will not be removed. It requires that the sub-attribute 'value' is also populated.

**Expected behavior**

I would expect that the 'display' attribute would be enough to identify the user and apply the operation passed in the request.

**Screenshots**
```json
{ "schemas":
       ["urn:ietf:params:scim:api:messages:2.0:PatchOp"],
     "Operations":[
       {
        "op":"add",
        "path":"members",
        "value":[
         {
           "display": "Babs.Jensen@example.com"
         }
        ]
       },
     ]
   }
```
**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by thomaspoignant** [comment]
Hello @KareemMasoud, thanks for opening this issue, I will try to help you with that.
Can you provide me an example of the SCIM entity you try to patch so I will be able to reproduce the issue on my side?

**Comment by thomaspoignant** [comment]
Hi @KareemMasoud, I have looked at your case in detail and I am not sure this is a bug.  
What I read in the RFC here https://datatracker.ietf.org/doc/html/rfc7644#section-3.5.2.1 is:

> If the target location already contains the value specified, no changes SHOULD be made to the resource, and a success response SHOULD be returned.  Unless other operations change the resource, this operation SHALL NOT change the modify timestamp of the resource.

In your case, the object you provide is different from the one in the array because it does not have all the same fields in it. So this is seen as a different object so we **add** it, if I correctly understand your expectation you wanted that we **replace** it instead?

Since there are no such things as primary key in SCIM it is impossible to know if we should **replace** of **add** when we have a partial object like what you said.

Did I miss something in the RFC?
Are you aligned with my explanation?
