### ISSUE TITLE
Replace operations for attributes that do not exist should be treated as an add

### ISSUE THREAD

**Issue by xtellurian** [thomaspoignant/scim-patch#381]
Active Directory sends SCIM messages with `type=replace` for attributes that do not exist.

I'd like to be able to control whether those replace messages are handled as `add`s.

I considered adding my own checks for this case outside this library, but
a) It would make for ugly code
b) It seems like others may encounter this issue

The relevant part of the spec is:
https://www.rfc-editor.org/rfc/rfc7644#section-3.5.2.3

> If the target location path specifies an attribute that does not
      exist, the service provider SHALL treat the operation as an "add".

**Comment by thomaspoignant** [comment]
This feature is released in version `v0.7.0` of the lib.

**Comment by yubing24** [comment]
@thomaspoignant In both README and the test, in order to treat replacing missing value as add, an optional configuration has to be explicitly passed to `scimPatch` function: ```const patchedUser = scimPatch(scimUser, patch, {treatMissingAsAdd: true});```

The RFC states that this `SHALL` be implemented, which means that it's an absolute requirement of the specification per RFC 2119: https://www.rfc-editor.org/rfc/rfc2119#section-1

Would you consider making this the default behavior rather than an optional feature that has to be explicitly specified by developers? What are the reasons that this is being treated as an optional feature rather than the default?

**Comment by yubing24** [comment]
I can look into it, but I won't be able to get on it anytime soon.

**Comment by thomaspoignant** [comment]
@yubing24 I will check and prepare a PR for this.

**Comment by thomaspoignant** [comment]
The PR is available https://github.com/thomaspoignant/scim-patch/pull/448
